name = "Trixi2Vtk"
uuid = "bc1476a1-1ca6-4cc3-950b-c312b255ff95"
authors = ["Michael Schlottke-Lakemper <michael@sloede.com>", "Hendrik Ranocha <mail@ranocha.de>"]
version = "0.3.28-dev"

[deps]
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
EllipsisNotation = "1.0"
Glob = "1.3"
HDF5 = "0.14, 0.15, 0.16, 0.17"
ProgressMeter = "1.3"
StaticArrays = "0.12, 1.0"
TimerOutputs = "0.5"
Trixi = "0.9, 0.10, 0.11, 0.12, 0.13"
WriteVTK = "1.7"
julia = "1.10"
